repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: no-commit-to-branch
        args: ["--branch", "main", "--branch", "develop"]
      - id: detect-private-key
      - id: check-added-large-files
        args: ["--maxkb", "1000"]

  - repo: local
    hooks:
      - id: build
        name: Build
        entry: make build
        language: system
        pass_filenames: false
